[package]
name = "linera-views-derive"
version = "0.1.0"
authors = ["Linera <contact@linera.io>"]
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { workspace = true, features = ["full", "extra-traits"] }
quote = { workspace = true }
proc-macro2 = { workspace = true }
convert_case = { workspace = true }
serde = { workspace = true }
async-graphql = { workspace = true }
