[package]
name = "linera-chain"
version = "0.1.0"
authors = ["Linera <contact@linera.io>"]
edition = "2021"

[features]
test = ["tokio/macros", "async-lock", "linera-base/test", "linera-execution/test"]

[dependencies]
async-trait = { workspace = true }
async-lock = { version = "2.6.0", optional = true }
async-graphql = { workspace = true }
linera-base = { workspace = true }
linera-execution = { workspace = true }
linera-views = { workspace = true, features = ["metrics"] }
tracing = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
linera-chain = { workspace = true, features = ["test"] }

[package.metadata.cargo-machete]
ignored = ["async-trait"]
