resource get {
    static new: func() -> get
    poll: func() -> poll-get
}

variant poll-get {
    pending,
    ready(list<u8>),
}

resource set {
    static new: func(value: list<u8>) -> set
    poll: func() -> poll-set
}

variant poll-set {
    pending,
    ready,
}

