[package]
name = "linera-contracts"
version = "0.1.0"
authors = ["Linera <contact@linera.io>"]
edition = "2021"

[features]
wasmer = ["dep:wasmer", "wit-bindgen-wasmer"]
wasmtime = ["dep:wasmtime", "wit-bindgen-host-wasmtime-rust"]

[dependencies]
anyhow = "1.0.65"
wasmer = { git = "https://github.com/wasmerio/wasmer", optional = true }
wasmtime = { version = "1.0.0", optional = true }
wit-bindgen-host-wasmtime-rust = { git = "https://github.com/bytecodealliance/wit-bindgen", optional = true }
wit-bindgen-wasmer = { git = "https://github.com/wasmerio/wit-bindgen", optional = true }
