package linera:app;

interface contract-entrypoints {
    initialize: func(context: operation-context, argument: list<u8>) -> result<raw-execution-outcome, string>;
    execute-operation: func(context: operation-context, operation: list<u8>) -> result<raw-execution-outcome, string>;
    execute-message: func(context: message-context, message: list<u8>) -> result<raw-execution-outcome, string>;
    handle-application-call: func(context: callee-context, argument: list<u8>, forwarded-sessions: list<session-id>) -> result<application-call-outcome, string>;
    handle-session-call: func(context: callee-context, session-state: list<u8>, argument: list<u8>, forwarded-sessions: list<session-id>) -> result<tuple<session-call-outcome, list<u8>>, string>;

    record message-context {
        chain-id: chain-id,
        is-bouncing: bool,
        authenticated-signer: option<owner>,
        refund-grant-to: option<account>,
        height: block-height,
        certificate-hash: crypto-hash,
        message-id: message-id,
    }

    record chain-id {
        inner0: crypto-hash,
    }

    record account {
        chain-id: chain-id,
        owner: option<owner>,
    }

    record resources {
        fuel: u64,
        read-operations: u32,
        write-operations: u32,
        bytes-to-read: u32,
        bytes-to-write: u32,
        messages: u32,
        message-size: u32,
        storage-size-delta: u32,
    }

    record operation-context {
        chain-id: chain-id,
        authenticated-signer: option<owner>,
        height: block-height,
        index: u32,
        next-message-index: u32,
    }

    record channel-name {
        inner0: list<u8>,
    }

    record session-id {
        application-id: application-id,
        index: u64,
    }

    record raw-outgoing-message {
        destination: destination,
        authenticated: bool,
        grant: resources,
        kind: message-kind,
        message: list<u8>,
    }

    record bytecode-id {
        message-id: message-id,
    }

    record session-call-outcome {
        inner: application-call-outcome,
        close-session: bool,
    }

    record application-id {
        bytecode-id: bytecode-id,
        creation: message-id,
    }

    record crypto-hash {
        part1: u64,
        part2: u64,
        part3: u64,
        part4: u64,
    }

    record callee-context {
        chain-id: chain-id,
        authenticated-signer: option<owner>,
        authenticated-caller-id: option<application-id>,
    }

    record raw-execution-outcome {
        authenticated-signer: option<owner>,
        refund-grant-to: option<account>,
        messages: list<raw-outgoing-message>,
        subscribe: list<tuple<channel-name, chain-id>>,
        unsubscribe: list<tuple<channel-name, chain-id>>,
    }

    variant destination {
        recipient(chain-id),
        subscribers(channel-name),
    }

    record application-call-outcome {
        value: list<u8>,
        execution-outcome: raw-execution-outcome,
        create-sessions: list<list<u8>>,
    }

    record owner {
        inner0: crypto-hash,
    }

    record message-id {
        chain-id: chain-id,
        height: block-height,
        index: u32,
    }

    enum message-kind {
        simple,
        protected,
        tracked,
        bouncing,
    }

    record block-height {
        inner0: u64,
    }
}
