[package]
name = "linera-views"
version = "0.1.0"
authors = ["Linera <contact@linera.io>"]
edition = "2021"

[features]
test = ["anyhow", "tokio/macros", "tokio/parking_lot"]
aws = ["aws-config", "aws-sdk-dynamodb", "aws-sdk-s3", "aws-smithy-http", "aws-types"]
db_timings = []
metrics = ["dep:hex", "dep:metrics"]

[dependencies]
static_assertions = { workspace = true }
async-lock = { workspace = true }
async-trait = { workspace = true }
bcs = { workspace = true }
futures = { workspace = true }
generic-array = { workspace = true }
hex = { workspace = true, optional = true }
linera-base = { workspace = true }
linera-views-derive = { workspace = true }
metrics = { workspace = true, optional = true }
serde = { workspace = true }
sha3 = { workspace = true }
thiserror = { workspace = true }
linked-hash-map = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { workspace = true, features = ["rt", "sync"] }
anyhow = { workspace = true, optional = true }
tracing = { workspace = true }
http = { workspace = true }
rand = { workspace = true }
rocksdb = { workspace = true }
aws-config = { workspace = true, optional = true }
aws-sdk-dynamodb = { workspace = true, optional = true }
aws-sdk-s3 = { workspace = true, optional = true }
aws-smithy-http = { workspace = true, optional = true }
aws-types = { workspace = true, optional = true }
tokio-test = { workspace = true }

[dev-dependencies]
linera-views = { workspace = true, features = ["test"] }
tempfile = { workspace = true }
