[package]
name = "crowd-funding"
version = "0.1.0"
authors = ["Linera <contact@linera.io>"]
edition = "2021"

[dependencies]
async-trait = "0.1.52"
bcs = "0.1.3"
fungible = { path = "../fungible" }
linera-sdk = { path = "../../linera-sdk" }
serde = { version = "1.0.130", features = ["derive"] }
thiserror = "1.0.31"

[[bin]]
name = "crowd-funding_contract"
path = "src/contract.rs"

[[bin]]
name = "crowd-funding_service"
path = "src/service.rs"
