[package]
name = "linera-sdk-wasm-tests"
version = "0.1.0"
authors = ["Linera <contact@linera.io>"]
edition = "2021"

[dev-dependencies]
linera-sdk = { path = "..", features = ["test"] }
log = "0.4.17"
webassembly-test = "0.1.0"
