[package]
name = "linera-sdk"
version = "0.1.0"
authors = ["Linera <contact@linera.io>"]
edition = "2021"

[features]
crypto = ["serde", "ed25519-dalek", "generic-array", "hex", "serde-name", "sha2", "thiserror"]
serde = ["bcs", "dep:serde", "serde_with"]

[dependencies]
async-trait = "0.1.52"
bcs = { version = "0.1.3", optional = true }
ed25519-dalek = { version = "1.0.1", features = ["batch", "serde"], optional = true }
generic-array = { version = "0.14.4", features = ["serde"], optional = true }
hex = { version = "0.4.3", optional = true }
serde = { version = "1.0.130", features = ["derive"], optional = true }
serde-name = { version = "0.2.0", optional = true }
serde_with = { version = "2.1.0", optional = true }
sha2 = { version = "0.9.8", optional = true }
thiserror = { version = "1.0.31", optional = true }

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
bcs = "0.1.3"
futures = "0.3.17"
serde = { version = "1.0.130", features = ["derive"] }
thiserror = "1.0.31"
wit-bindgen-guest-rust = { git = "https://github.com/jvff/wit-bindgen", rev = "4a9e7cc6899a9736e2a2d23dcfc4f8744b6107a1" }

[[example]]
name = "counter_contract"
path = "examples/counter/contract.rs"
crate-type = ["cdylib"]

[[example]]
name = "counter_service"
path = "examples/counter/service.rs"
crate-type = ["cdylib"]

[[example]]
name = "fungible_contract"
path = "examples/fungible/contract.rs"
crate-type = ["cdylib"]
required-features = ["crypto"]

[[example]]
name = "fungible_service"
path = "examples/fungible/service.rs"
crate-type = ["cdylib"]
required-features = ["crypto"]
