[package]
name = "linera-storage"
version = "0.1.0"
authors = ["Linera <contact@linera.io>"]
edition = "2021"

[features]
default = ["wasmer"]
test = ["tokio/rt", "tokio/test-util", "tokio/time", "linera-execution/test", "linera-views/test"]
wasmer = ["linera-execution/wasmer"]
wasmtime = ["linera-execution/wasmtime"]
aws = ["linera-views/aws"]

[dependencies]
async-lock = { workspace = true }
async-trait = { workspace = true }
bcs = { workspace = true }
dashmap = { workspace = true }
futures = { workspace = true }
linera-base = { workspace = true }
linera-chain = { workspace = true }
linera-execution = { workspace = true }
linera-views = { workspace = true, features = ["metrics"] }
metrics = { workspace = true }
tracing = { workspace = true }
rocksdb = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true, features = ["macros"] }

[dev-dependencies]
anyhow = { workspace = true }
linera-storage = { workspace = true, features = ["test"] }
tempfile = { workspace = true }
